
apiVersion: v1
kind: Pod
metadata:
  name: sample-init
  labels:
    app: web

spec:
  initContainers:
    - name: init-container
      image: ubuntu
      command: ["echo","This is an ubuntu image."]
    
    - name: init-busybox
      image: busybox
      command: ["echo","This is an busybox image."]

  containers:
    - name: compassionate-moore
      image: harshit0015/node-hello
      


   






